/* Буквар - the history cards. Pure data.                                       */
/*                                                                              */
/* Each card is a tiny picture book: a hook ("Did you know?"), two story pages, */
/* a Bulgarian line to read together, and a "Remember it?" question. The hook   */
/* is the one strange, true detail a child will still have next week - the      */
/* cherry-tree cannons, the bundle of sticks - and the question asks about it.  */
/*                                                                              */
/* `line` and `name` use only letters taught by mission `m` (0-based), the same */
/* rule as missions.js, checked by tools/bukvar-check.js. That is why Аспарух   */
/* opens late: his name needs Х. The English pages have no such limit.          */
/*                                                                              */
/* Legends are said to be legends ("The story goes..."). A child who remembers  */
/* a legend as fact has learned something wrong.                                */
/*                                                                              */
/* `year` sorts the album and feeds the timeline questions. It is always the    */
/* first year `when` shows (a birth year for a life), so the order a child is   */
/* marked on is the order the cards display. Traditions have no year.          */
/*                                                                              */
/* `clue` is the quiz's "Who am I?" and must not give the name away. `ask` is   */
/* the Remember it question: the first option after it is the right one.       */
"use strict";
window.BQ = window.BQ || {};

BQ.CARDS = [
  // ── Before Bulgaria ──────────────────────────────────────────────────────
  { id: "gold", m: 9, year: -300, when: "about 300 BC", e: "🏺", name: "Панагюрско съкровище", topic: "history",
    hook: "In 1949, three brothers digging for clay found nine cups and jugs made of pure gold!",
    pages: ["The gold was made more than 2,000 years ago by the Thracians, who lived in these lands long before Bulgaria.",
      "It weighs about 6 kilograms. Some jugs are shaped like the heads of animals. You can see it in museums today."],
    line: "Три брата намериха злато.",
    clue: "Three brothers found me while digging for clay.",
    ask: ["What were the three brothers digging for?", "Clay", "Treasure", "Potatoes"] },
  { id: "spartak", m: 5, year: -73, when: "73 BC", e: "⚔️", name: "Спартак", topic: "history",
    hook: "The most famous gladiator of ancient Rome came from the lands of today's Bulgaria.",
    pages: ["Spartacus was a Thracian. He was captured and forced to fight as a gladiator in Rome.",
      "In 73 BC he escaped and led an army of slaves against Rome. The story goes that he was born near today's town of Sandanski."],
    line: "Спартак е смел гладиатор.",
    clue: "I was a gladiator who fought against Rome.",
    ask: ["What was Spartacus forced to be?", "A gladiator", "A king", "A sailor"] },

  // ── The First Bulgarian State ────────────────────────────────────────────
  { id: "kubrat", m: 7, year: 632, when: "632", e: "🏹", name: "Хан Кубрат", topic: "history",
    hook: "The story goes that Khan Kubrat showed his sons that a bundle of sticks can't be broken.",
    pages: ["Kubrat ruled Old Great Bulgaria, by the Black Sea. Before he died, he gave his five sons a bundle of sticks. Nobody could break it.",
      "Then he gave each son one stick, and they snapped easily. \"Stay together,\" he said, \"and no one can break you.\""],
    line: "Хан Кубрат има пет сина.",
    clue: "I taught my sons that sticks together can't be broken.",
    ask: ["What did Kubrat ask his sons to break?", "A bundle of sticks", "A sword", "A big rock"] },
  { id: "asparuh", m: 7, year: 681, when: "681", e: "🐎", name: "Хан Аспарух", topic: "history",
    hook: "Bulgaria is one of the oldest countries in Europe. It began in 681!",
    pages: ["Asparuh was one of Kubrat's five sons. He led his people across the great river Danube.",
      "He beat the Byzantine army, and in 681 the emperor made peace with him. That was the start of the Bulgarian state. Its first capital was Pliska."],
    line: "Хан Аспарух основа нова държава.",
    clue: "I crossed the Danube and started the Bulgarian state.",
    ask: ["Which river did Asparuh cross?", "The Danube", "The Nile", "The Thames"] },
  { id: "tervel", m: 4, year: 700, when: "700–721", e: "👑", name: "Тервел", topic: "history",
    hook: "Khan Tervel was the first foreign ruler the Byzantines ever called \"Caesar\".",
    pages: ["In 705 Tervel helped a Byzantine emperor win back his throne, and got the title Caesar as a thank-you.",
      "In 717 a huge Arab army surrounded the city of Constantinople. Tervel's riders came and beat them. Some call him the saviour of Europe."],
    line: "Тервел е смел воин.",
    clue: "The Byzantines called me Caesar, and I saved their city in 717.",
    ask: ["Which city did Tervel help save?", "Constantinople", "Rome", "Paris"] },
  { id: "madara", m: 8, year: 710, when: "about 710", e: "🏇", name: "Мадарски конник", topic: "history",
    hook: "A giant horseman is carved into a cliff, 23 metres above the ground!",
    pages: ["The Madara Rider shows a rider on a horse, spearing a lion. A dog runs behind him.",
      "It was carved about 1,300 years ago. It is on the UNESCO list of the world's treasures, and it is on Bulgaria's coins."],
    line: "Конникът е на скалата.",
    clue: "I am a rider carved into a cliff, spearing a lion.",
    ask: ["What animal is the rider spearing?", "A lion", "A dragon", "A bear"] },
  { id: "krum", m: 3, year: 803, when: "803–814", e: "📜", name: "Крум", topic: "history",
    hook: "Khan Krum wrote down Bulgaria's very first laws.",
    pages: ["Krum's laws were strict. People who stole were punished hard, and everyone had to help the poor so they would not need to steal.",
      "Krum made Bulgaria big and strong. In 811 he beat a huge Byzantine army in the mountains."],
    line: "Крум е силен и умен.",
    clue: "I wrote down Bulgaria's first laws.",
    ask: ["What did Krum write down first?", "Bulgaria's laws", "A song", "A map"] },
  { id: "boris", m: 6, year: 864, when: "864", e: "⛪", name: "Борис Първи", topic: "history",
    hook: "Boris stopped being a monk for a while to stop his own son!",
    pages: ["In 864 Boris made Bulgaria a Christian country. Later he gave the throne to his son Vladimir and became a monk.",
      "But Vladimir tried to bring back the old gods. Boris left the monastery, stopped him, put his other son Simeon on the throne, and went back to being a monk."],
    line: "Борис покръсти народа.",
    clue: "I made Bulgaria Christian in 864, then became a monk.",
    ask: ["Why did Boris leave the monastery?", "To stop his son", "To go on holiday", "To build a castle"] },
  { id: "cyril", m: 8, year: 863, when: "863", e: "✍️", name: "Кирил и Методий", topic: "history",
    hook: "On 24 May, Bulgarian children bring flowers to school to thank two brothers.",
    pages: ["Cyril and Methodius were brothers who made the first alphabet for Slavic languages. It is called Glagolitic.",
      "Their students came to Bulgaria. There a new alphabet was made, and named Cyrillic after Cyril. It's the one you are learning!"],
    line: "Кирил и Методий създадоха азбука.",
    clue: "We are two brothers who made the first Slavic alphabet.",
    ask: ["What do Bulgarians celebrate on 24 May?", "The alphabet and learning", "The first snow", "The harvest"] },
  { id: "kliment", m: 7, year: 886, when: "about 886", e: "🏫", name: "Климент Охридски", topic: "history",
    hook: "Kliment taught about 3,500 students to read and write!",
    pages: ["Kliment was a student of Cyril and Methodius. Knyaz Boris welcomed him to Bulgaria and sent him to teach.",
      "He trained teachers and priests, who spread books in the new letters. Sofia University is named after him."],
    line: "Климент учи децата да четат.",
    clue: "I taught about 3,500 students, and Sofia University has my name.",
    ask: ["About how many students did Kliment teach?", "About 3,500", "About 10", "About a million"] },
  { id: "rilski", m: 7, year: 876, when: "about 876–946", e: "⛰️", name: "Иван Рилски", topic: "history",
    hook: "Ivan of Rila lived all alone in a cave, high in the mountains.",
    pages: ["He wanted a quiet life of prayer, so he went into the Rila mountains. People heard he was wise and kind, and came to see him.",
      "His followers built a monastery there. Today the Rila Monastery is the most famous in Bulgaria."],
    line: "Иван Рилски е светец.",
    clue: "I lived alone in a mountain cave, and a famous monastery grew there.",
    ask: ["Where did Ivan of Rila live?", "In a cave in the mountains", "In a palace", "On a ship"] },
  { id: "simeon", m: 7, year: 893, when: "893–927", e: "📚", name: "Цар Симеон", topic: "history",
    hook: "As a boy Simeon studied in Constantinople. He spoke Greek so well he was called \"half-Greek\".",
    pages: ["Back home he became tsar. His time is called the Golden Age: writers in the capital, Preslav, made hundreds of books.",
      "Bulgaria grew so big that it reached three seas: the Black Sea, the Aegean and the Adriatic."],
    line: "При цар Симеон има много книги.",
    clue: "My time as tsar is called the Golden Age.",
    ask: ["What is Simeon's time called?", "The Golden Age", "The Ice Age", "The Stone Age"] },

  // ── The Second Bulgarian State ───────────────────────────────────────────
  { id: "asen", m: 6, year: 1185, when: "1185", e: "🛡️", name: "Асен и Петър", topic: "history",
    hook: "Two brothers started a rebellion in Tarnovo, and Bulgaria was free again.",
    pages: ["For 167 years Bulgaria was ruled by Byzantium. In 1185 the brothers Asen and Peter called the people to rise up.",
      "They won, and Tarnovo became the new capital. This was the start of the Second Bulgarian State."],
    line: "Асен и Петър вдигат въстание.",
    clue: "We are two brothers who freed Bulgaria in 1185.",
    ask: ["Which town became the new capital?", "Tarnovo", "London", "Varna"] },
  { id: "kaloyan", m: 9, year: 1205, when: "1205", e: "🏰", name: "Цар Калоян", topic: "history",
    hook: "Tsar Kaloyan beat the Crusader knights and captured their emperor!",
    pages: ["In 1204 knights from Western Europe took Constantinople and made their own emperor, Baldwin.",
      "Then they attacked Bulgaria. In 1205, near Adrianople, Kaloyan beat them and took Emperor Baldwin prisoner."],
    line: "Калоян победи рицарите.",
    clue: "I captured the Crusaders' emperor in 1205.",
    ask: ["Who did Kaloyan capture?", "An emperor", "A dragon", "A pirate"] },
  { id: "ivanasen", m: 7, year: 1230, when: "1230", e: "🤲", name: "Цар Иван Асен Втори", topic: "history",
    hook: "Ivan Asen II rode into battle with a broken peace treaty tied to his flag.",
    pages: ["His neighbour Theodore broke their peace treaty and attacked. In 1230 at Klokotnitsa, Ivan Asen won a great battle.",
      "Then he let the captured soldiers go home. People loved him for being kind, and Bulgaria again reached three seas."],
    line: "Цар Иван Асен е добър владетел.",
    clue: "I tied a broken treaty to my flag, and let my prisoners go home.",
    ask: ["What did Ivan Asen II do with the soldiers he captured?", "Let them go home", "Made them build a wall", "Sent them to sea"] },

  // ── The Revival and Liberation ───────────────────────────────────────────
  { id: "paisiy", m: 8, year: 1762, when: "1762", e: "🖋️", name: "Паисий", topic: "history",
    hook: "Paisiy was cross that some Bulgarians were ashamed of being Bulgarian.",
    pages: ["He was a monk on Mount Athos. He collected old books and wrote a history of the Bulgarians, to show them how proud they could be.",
      "There were no printers, so people copied his book by hand and passed it on for years. It woke up the whole nation."],
    line: "Паисий написа книга за нашите царе и светци.",
    clue: "I was a monk who wrote a history book in 1762.",
    ask: ["How did people share Paisiy's book?", "They copied it by hand", "On the radio", "On TV"] },
  { id: "aprilov", m: 8, year: 1835, when: "1835", e: "🎒", name: "Васил Априлов", topic: "history",
    hook: "Vasil Aprilov paid for the first modern Bulgarian school.",
    pages: ["He was a merchant who lived far from home. He wanted Bulgarian children to learn in their own language.",
      "In 1835 the school opened in Gabrovo. Soon towns all over the country opened schools like it."],
    line: "Априлов отвори ново училище.",
    clue: "I paid for the first modern Bulgarian school, in Gabrovo.",
    ask: ["Which town got the first modern school?", "Gabrovo", "Paris", "Sydney"] },
  { id: "rakovski", m: 5, year: 1821, when: "1821–1867", e: "🗺️", name: "Георги Раковски", topic: "history",
    hook: "Rakovski made the first plan to free Bulgaria with an army of volunteers.",
    pages: ["In 1862 in Belgrade he gathered young Bulgarians into the First Bulgarian Legion, to train them to fight.",
      "One of those young men was Vasil Levski."],
    line: "Раковски е бунтовник.",
    clue: "I started the First Bulgarian Legion in Belgrade.",
    ask: ["Which famous hero was in Rakovski's legion?", "Vasil Levski", "Khan Krum", "Tsar Simeon"] },
  { id: "levski", m: 4, year: 1837, when: "1837–1873", e: "🦁", name: "Васил Левски", topic: "history",
    hook: "The story goes that he got the name Levski, \"like a lion\", after a huge jump.",
    pages: ["Levski travelled from village to village in disguise. He set up secret groups, getting people ready to fight for freedom.",
      "He was caught in 1873 and gave his life for Bulgaria. He is called the Apostle of Freedom."],
    line: "Левски е Апостола на свободата.",
    clue: "I am called the Apostle of Freedom.",
    ask: ["What does the name Levski mean?", "Like a lion", "Like a bear", "Like the wind"] },
  { id: "rayna", m: 9, year: 1876, when: "1876", e: "🚩", name: "Райна Княгиня", topic: "history",
    hook: "Rayna sewed the flag of the April Uprising with the words \"Freedom or death\".",
    pages: ["Rayna was a teacher in the town of Panagyurishte. She sewed a golden lion onto the flag.",
      "People called her Rayna Knyaginya, which means Rayna the Princess."],
    line: "Райна уши знаме.",
    clue: "I sewed the flag of the April Uprising.",
    ask: ["What words were sewn on Rayna's flag?", "Freedom or death", "Happy birthday", "Welcome home"] },
  { id: "april", m: 6, year: 1876, when: "1876", e: "🍒", name: "Априлското въстание", topic: "history",
    hook: "The rebels made cannons out of cherry tree trunks!",
    pages: ["In April 1876 Bulgarians in many towns rose up for freedom. They had few weapons, so they made their own.",
      "The uprising was crushed, but newspapers told the whole world what happened, and many countries began to help."],
    line: "През април народът въстана за свобода.",
    clue: "I happened in spring 1876, with cannons made of cherry wood.",
    ask: ["What did the rebels make cannons from?", "Cherry trees", "Old pots", "Ice"] },
  { id: "botev", m: 7, year: 1848, when: "1848–1876", e: "🚢", name: "Христо Ботев", topic: "history",
    hook: "Botev and his fighters took over a steamship on the Danube!",
    pages: ["They got on the ship Radetzky as passengers, then made the captain take them to the Bulgarian shore. There they kissed the ground.",
      "Botev also wrote poems children still learn. Every 2 June at 12 o'clock, sirens sound for a minute to remember him."],
    line: "Ботев е поет и бунтовник.",
    clue: "I was a poet who took over a ship to fight for freedom.",
    ask: ["What happens every 2 June at 12 o'clock?", "Sirens sound for a minute", "Fireworks", "Everyone sings"] },
  { id: "shipka", m: 6, year: 1877, when: "1877", e: "🏔️", name: "Шипка", topic: "history",
    hook: "When the bullets ran out, the defenders threw rocks and logs down the mountain!",
    pages: ["In August 1877 a small group of Bulgarian volunteers and Russian soldiers held Shipka Pass.",
      "A much bigger army attacked for days, but could not get through. A tall monument stands on the peak today."],
    line: "На Шипка се води битка.",
    clue: "I am a mountain pass where volunteers held back a huge army.",
    ask: ["What did the defenders throw when the bullets ran out?", "Rocks and logs", "Snowballs", "Flowers"] },
  { id: "liberation", m: 5, year: 1878, when: "3 March 1878", e: "🎉", name: "Освобождението", topic: "history",
    hook: "3 March is Bulgaria's national day. Here's why.",
    pages: ["After a war between Russia and the Ottoman Empire, a peace was signed on 3 March 1878.",
      "Bulgaria was free again after almost 500 years. In Sofia a monument called the Tsar Liberator remembers it."],
    line: "Трети март е Освобождението.",
    clue: "I happened on 3 March, and now it is a holiday.",
    ask: ["What date is Bulgaria's national day?", "3 March", "1 January", "25 December"] },
  { id: "union", m: 6, year: 1885, when: "1885", e: "🤝", name: "Съединението", topic: "history",
    hook: "\"Unity makes strength\" is written on the Parliament building. It comes from 1885.",
    pages: ["After 1878 Bulgaria was split in two. On 6 September 1885 the people of Plovdiv joined the two halves, without a fight.",
      "Serbia attacked soon after, but the Bulgarian army won at Slivnitsa in about two weeks."],
    line: "Съединението прави силата.",
    clue: "In 1885 two parts of a country became one.",
    ask: ["What does the motto on the Parliament say?", "Unity makes strength", "Money makes friends", "Stay at home"] },
  { id: "aleko", m: 6, year: 1895, when: "1895", e: "🥾", name: "Алеко Константинов", topic: "history",
    hook: "Aleko took about 300 people up a mountain, and started hiking clubs in Bulgaria!",
    pages: ["In 1895 he led the climb up Cherni Vrah, the top of Mount Vitosha, near Sofia. That was the start of the Bulgarian tourist clubs.",
      "He also wrote funny stories about a man called Bay Ganyo."],
    line: "Алеко обича планината.",
    clue: "I took 300 people up Vitosha and started hiking clubs.",
    ask: ["Which mountain did Aleko climb with 300 people?", "Vitosha", "Everest", "Kilimanjaro"] },
  { id: "vazov", m: 5, year: 1850, when: "1850–1921", e: "📖", name: "Иван Вазов", topic: "art",
    hook: "Ivan Vazov is called the Patriarch, the grandfather, of Bulgarian writing.",
    pages: ["He wrote Under the Yoke, a novel about the April Uprising. It has been translated into dozens of languages.",
      "He also wrote The Epic of the Forgotten, poems about heroes like Levski."],
    line: "Вазов е писател.",
    clue: "I wrote the novel Under the Yoke.",
    ask: ["What is Vazov's famous novel called?", "Under the Yoke", "Harry Potter", "The Hobbit"] },
  { id: "independence", m: 5, year: 1908, when: "22 September 1908", e: "🗝️", name: "Независимостта", topic: "history",
    hook: "Even after 1878, Bulgaria still had to answer to the Ottoman sultan. Until 1908.",
    pages: ["On 22 September 1908, in the old capital Veliko Tarnovo, Bulgaria said it was fully independent.",
      "22 September is a holiday now: Independence Day."],
    line: "На 22 септември е Независимостта.",
    clue: "I was declared in Veliko Tarnovo on 22 September 1908.",
    ask: ["Where was Independence declared?", "Veliko Tarnovo", "Varna", "London"] },

  // ── Science and art ──────────────────────────────────────────────────────
  { id: "grigorov", m: 5, year: 1905, when: "1905", e: "🔬", name: "Стамен Григоров", topic: "science",
    hook: "The tiny helper that turns milk into yogurt is named after Bulgaria!",
    pages: ["Stamen Grigorov was a young Bulgarian doctor, studying in Geneva. In 1905 he looked at Bulgarian yogurt under a microscope.",
      "He found the bacterium that makes it. It is called Lactobacillus bulgaricus."],
    line: "Григоров гледа в микроскоп.",
    clue: "I found the bacterium that makes yogurt.",
    ask: ["What did Grigorov discover?", "The yogurt bacterium", "A new planet", "A dinosaur"] },
  { id: "atanasoff", m: 8, year: 1939, when: "1939", e: "💻", name: "Джон Атанасов", topic: "science",
    hook: "The idea for one of the first computers came to him on a long night drive.",
    pages: ["John Atanasoff's father came from a village near Yambol, in Bulgaria.",
      "In 1939, with his student Clifford Berry, John began building one of the first electronic computers in the world."],
    line: "Атанасов е създател на един от първите компютри.",
    clue: "My father was Bulgarian, and I built one of the first computers.",
    ask: ["Where did Atanasoff's father come from?", "Bulgaria", "Japan", "Brazil"] },
  { id: "ivanov", m: 5, year: 1979, when: "1979", e: "🛰️", name: "Георги Иванов", topic: "science",
    hook: "In 1979 Bulgaria became the sixth country to send a person into space.",
    pages: ["Georgi Ivanov was a pilot. He flew on the spaceship Soyuz 33.",
      "The engine broke, so the crew had to come back to Earth early. But they landed safely!"],
    line: "Иванов лети в космоса.",
    clue: "I was the first Bulgarian in space.",
    ask: ["What went wrong on his space flight?", "The engine broke", "They got lost", "It rained"] },
  { id: "christo", m: 9, year: 1935, when: "1935–2020", e: "🎁", name: "Христо Явашев", topic: "art",
    hook: "Christo wrapped a whole parliament building in silver cloth!",
    pages: ["He was born in Gabrovo and became an artist, known simply as Christo. With his wife Jeanne-Claude he made giant works of art.",
      "In 1995 they wrapped the Reichstag in Berlin. They also wrapped a bridge in Paris, and made paths that floated on a lake in Italy."],
    line: "Христо е художник.",
    clue: "I wrapped a parliament building in silver cloth.",
    ask: ["What did Christo wrap in Berlin?", "A parliament building", "A car", "A tree"] },

  // ── Sport ────────────────────────────────────────────────────────────────
  { id: "levskifc", m: 7, year: 1914, when: "1914", e: "💙", name: "ФК Левски", topic: "sport",
    hook: "In 1914 some students in Sofia started a football club and named it after Vasil Levski.",
    pages: ["Levski plays in blue, so its fans are called \"the Blues\", сините.",
      "Levski has played in the top league every single season and has never been relegated. Its home is the Georgi Asparuhov Stadium."],
    line: "Левски е отбор на сините.",
    clue: "I am a football club in blue, named after a hero.",
    ask: ["Who is the club named after?", "Vasil Levski", "A lion", "A river"] },
  { id: "gundi", m: 7, year: 1943, when: "1943–1971", e: "⚽", name: "Георги Аспарухов", topic: "sport",
    hook: "Fans called him Gundi. He was voted Bulgaria's best footballer of the 20th century.",
    pages: ["He was a tall striker for Levski who scored with his head and both feet. He played at three World Cups: 1962, 1966 and 1970.",
      "The story goes that big clubs abroad wanted him, but he stayed with Levski. He died young, in 1971, and Levski's stadium is named after him."],
    line: "Гунди е легенда на Левски.",
    clue: "Fans called me Gundi, and Levski's stadium has my name.",
    ask: ["What is named after Gundi?", "Levski's stadium", "A mountain", "A ship"] },
  { id: "kostadinova", m: 8, year: 1987, when: "1987", e: "🏅", name: "Стефка Костадинова", topic: "sport",
    hook: "Stefka jumped 2.09 metres high, and no woman jumped higher for 37 years!",
    pages: ["She set the high jump world record in Rome in 1987. It lasted until 2024.",
      "In 1996 she also won Olympic gold in Atlanta."],
    line: "Стефка скача много високо.",
    clue: "My high jump world record lasted 37 years.",
    ask: ["How long did her world record last?", "37 years", "1 week", "5 minutes"] },
  { id: "stoichkov", m: 9, year: 1994, when: "1994", e: "🥇", name: "Христо Стоичков", topic: "sport",
    hook: "In 1994 Stoichkov won the Golden Ball: the prize for the best footballer in Europe.",
    pages: ["He played for Barcelona. At the 1994 World Cup in the USA, Bulgaria beat Germany and reached the semi-final.",
      "Stoichkov scored six goals and shared the Golden Boot for top scorer."],
    line: "Стоичков е велик футболист.",
    clue: "I won the Golden Ball in 1994.",
    ask: ["Which famous team did Stoichkov play for?", "Barcelona", "The Chicago Bulls", "A rugby team"] },
  { id: "topalov", m: 8, year: 2005, when: "2005", e: "♟️", name: "Веселин Топалов", topic: "sport",
    hook: "In 2005 Veselin Topalov became world chess champion.",
    pages: ["He learned chess from his father when he was eight.",
      "He won the FIDE World Championship in Argentina in 2005, and was number one in the world."],
    line: "Топалов е шампион по шах.",
    clue: "I became world chess champion in 2005.",
    ask: ["What game is Topalov a champion of?", "Chess", "Football", "Tennis"] },
  { id: "berbatov", m: 6, year: 2010, when: "2010", e: "🎯", name: "Димитър Бербатов", topic: "sport",
    hook: "Berbatov once scored five goals in one Premier League match!",
    pages: ["He played for Manchester United. In November 2010 he scored all five of their goals against Blackburn.",
      "That season he was joint top scorer of the whole Premier League."],
    line: "Бербатов вкара пет гола.",
    clue: "I scored five goals in one Premier League match.",
    ask: ["How many goals did Berbatov score in one match?", "Five", "One", "Twenty"] },
  { id: "grigor", m: 8, year: 2017, when: "2017", e: "🎾", name: "Григор Димитров", topic: "sport",
    hook: "In 2017 Grigor Dimitrov beat the best tennis players in the world at the ATP Finals.",
    pages: ["He comes from Haskovo. His father was a tennis coach and gave him his first racket when he was three.",
      "After his win in 2017 he was number three in the world."],
    line: "Григор е тенисист.",
    clue: "I won the ATP Finals in tennis in 2017.",
    ask: ["Who taught Grigor tennis first?", "His father", "A robot", "His dog"] },

  // ── Traditions ───────────────────────────────────────────────────────────
  { id: "martenitsa", m: 4, year: null, when: "Every 1 March", e: "🧶", name: "Баба Марта", topic: "tradition",
    hook: "On 1 March, Bulgarians tie red and white threads on each other for luck and health.",
    pages: ["They are called martenitsi. Grandma March (Баба Марта) brings spring, and the threads keep her happy.",
      "When you see a stork or a tree in blossom, you take your martenitsa off and tie it to a branch."],
    line: "Баба Марта е тук!",
    clue: "I bring spring on 1 March, with red and white threads.",
    ask: ["When do you take your martenitsa off?", "When you see a stork or blossom", "At bedtime", "On your birthday"] },
  { id: "kukeri", m: 9, year: null, when: "Every winter", e: "🔔", name: "Кукери", topic: "tradition",
    hook: "In winter, men in giant furry masks dance and ring huge bells to scare away evil.",
    pages: ["The kukeri wear costumes of fur and bright colours, and heavy bells on their belts.",
      "They dance through the village to chase bad spirits away and bring a good harvest. The biggest festival is in Pernik."],
    line: "Кукерите гонят злото.",
    clue: "We wear furry masks and bells to scare away evil.",
    ask: ["Why do the kukeri ring their bells?", "To scare away evil", "To call the cows", "To start school"] },
  { id: "roses", m: 8, year: null, when: "Every June", e: "🌹", name: "Розовата долина", topic: "tradition",
    hook: "It takes about 3,000 kilograms of rose petals to make just 1 kilogram of rose oil!",
    pages: ["Near Kazanlak is the Rose Valley. Bulgaria makes a big part of the world's rose oil, used in perfume.",
      "The petals are picked by hand, early in the morning. Every June there is a Rose Festival."],
    line: "Розите са красиви.",
    clue: "I am a valley famous for roses and rose oil.",
    ask: ["How many kilos of petals make 1 kilo of rose oil?", "About 3,000", "About 2", "About 10"] }
];

// The passport. One stamp per mission from 2 to 10, earned by a perfect quiz
// on everything taught up to that mission. `m` is the mission (0-based) that
// opens it. Place names are decoration, not something the child has to read.
BQ.STAMPS = [
  { m: 1, place: "София", ink: "#2f6fd6", fact: "Bulgaria's capital city today." },
  { m: 2, place: "Созопол", ink: "#0e8fa8", fact: "A town by the Black Sea, more than 2,500 years old." },
  { m: 3, place: "Плиска", ink: "#b3541e", fact: "Bulgaria's first capital, from 681." },
  { m: 4, place: "Карлово", ink: "#7a3fb8", fact: "The town where Vasil Levski was born." },
  { m: 5, place: "Пловдив", ink: "#c0392b", fact: "One of the oldest cities in Europe. Ivan Vazov lived here." },
  { m: 6, place: "Копривщица", ink: "#1f8a4c", fact: "The April Uprising began here in 1876." },
  { m: 7, place: "Преслав", ink: "#a0522d", fact: "Tsar Simeon's capital, and home of a famous school of writers." },
  { m: 8, place: "Рилски манастир", ink: "#5b4bb7", fact: "Bulgaria's most famous monastery, over 1,000 years old." },
  { m: 9, place: "Велико Търново", ink: "#b8860b", fact: "Capital of the Second Bulgarian Empire, on the Yantra river." }
];
